package com.company;

public class Main {

    public static void main(String[] args) {

        boolean isDone = false;
        int inc = 2;
        long i = 1;
        while(!isDone)
        {
            i += inc;
            if(isPentagonal(i) && isHexagonal(i) && i != 40755)
            {
                System.out.println(i);
                break;
            }
            System.out.println(i);
            inc++;
        }
    }

    private static boolean isPentagonal(long n)
    {
        double pen = Math.sqrt(24*n+1);
        return (pen % 6 == 5);
    }

    private static boolean isHexagonal(long n)
    {
        double hex = (Math.sqrt(8*n+1)+1)/4;
        return hex == (long) hex;
    }


}
//Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
//Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
//Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
//Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
//It can be verified that T285 = P165 = H143 = 40755.
//
//Find the next triangle number that is also pentagonal and hexagonal.